baseURL: "https://avinashdharan.com/"
title: Avinash
paginate: 5
theme: ["PaperMod"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: G-BLWKRK13HN
  
minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Avinash Personal site
    description: "Personal site of Avinash"
#    keywords: [Blog, Portfolio, PaperMod]
    keywords: [Portfolio]
   # author: Avins
    # author: ["Me", "You"] # multiple authors
    images: ["test.jpg"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: false
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    ShowFullTextinRSS: true

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "avinashdharan.com"
       # icon: /test.jpg
       # iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true# needs to be explicitly set
        title: Avinash Dharan
        subtitle: "An eclectic guy with Da Vinci's curse. SRE engineer by profession, always a student of life"
        imageUrl: "author.jpg"
        imageWidth: 210
        imageHeight: 200
        imageTitle: Author.jpg
        buttons:
            - name: Notes
              url: https://notes.avinashdharan.com/
            - name: About
              url: /about
            - name: Posts
              url: https://blog.avinashdharan.com/
#           - name: Today I learnt
#             url: /til

    # home-info mode
    homeInfoParams:
        Title: "Hey there!"
        Content: Welcome to my blog. I'm Avinash , SRE engineer by trade and student of life.

    socialIcons:
        - name: email
          url: mailto:avinashdharan@gmail.com
        - name: linkedin
          url: "https://www.linkedin.com/in/avinashdharan/"
        - name: telegram
          url: "https://t.me/avinashdharan"
        - name: github
          url: "https://github.com/avinashdharan"
        - name: rss
          url: "https://avinashdharan.com/index.xml"
       # - name: instagram
       #  url: "https://instagram.com/avinashdharan"

    # analytics:
    #     google:
    #         SiteVerificationTag: "G-BLWKRK13HN"
    #     bing:
    #         SiteVerificationTag: "XYZabc"
    #     yandex:
    #         SiteVerificationTag: "XYZabc"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

#    editPost:
#        URL: "https://github.com/avinashdharan/avinashdharan.com/content"
#        Text: "Suggest Changes" # edit text
#        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
#menu:
   # main:
      #  - identifier: Blog
      #   name: Blog
      #    url: https://blog.avinashdharan.com/
      #    weight: 10
      #  - identifier: Archives
      #    name: Archives
      #    url: /archives
      #    weight: 20
      #  - identifier: tags
      #    name: tags
      #    url: /tags/
      #    weight: 30
      #  - identifier: TIL
      #    name: TIL - Today I learnt
      #    url: /til
      #    weight: 20
      #  - identifier: About
      #    name: About
      #    url: /about
      #    weight: 30
          


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

#<script defer data-domain="avinashdharan.com" src="https://plausible.io/js/plausible.js"></script>
